project_id = "ortftjkeyriakevvolon"

[functions.gelato-api]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false
